### ISSUE TITLE
Unable to open manifest

### ISSUE THREAD

**Issue by Mclaren-720S** [Turnergamer/Boxel-Rebound#1]
No idea about coding whatsoever, but, does one know how to fix the lack of manifest

![image](https://user-images.githubusercontent.com/89882676/131623535-8d6ca7fa-65f5-4b6d-b370-e0d324ba476c.png)
(this is what came in the folder)

**Comment by Turnergamer** [comment]
Sorry you will find the extension here https://www.mediafire.com/file/vtb1sdwh1pc2vuo/iginnfkhmmfhlkagcmpgofnjhanpmklb.zip/file

**Comment by Turnergamer** [comment]
Please read the read me file !
