### ISSUE TITLE
Cosole Disabled

### ISSUE THREAD

**Issue by J0513-301** [Turnergamer/Boxel-Rebound#2]
I tried to inject the code but in the console, it says console disabled. I then realized I could still paste the code and I did however nothing happened. I then went to the elements to try and delete the console disabled code, however, this still did not work. I went to the Boxel Rebound online page and tried it there however it still did not work. I tried using SnowLord7's code before this one with similar results. How do I get around this?

**Comment by Turnergamer** [comment]
Use the extension and add it to chrome play it through that extension everything is still on it but console isn't disabled
